# Remove target files after command failure.
.DELETE_ON_ERROR:

models: \
		{% for wiki in wikis %}
			{{ wiki.name }}_models {% if not loop.last %}\{% endif %}
		{% endfor %}

tuning_reports: \
		{% for wiki in wikis %}
			{{ wiki.name }}_tuning_reports {% if not loop.last %}\{% endif %}
		{% endfor %}

test_statistics = \
		-s 'table' -s 'accuracy' -s 'precision' -s 'recall' \
		-s 'pr' -s 'roc' \
		-s 'recall_at_fpr(max_fpr=0.10)' \
		-s 'filter_rate_at_recall(min_recall=0.9)' \
		-s 'filter_rate_at_recall(min_recall=0.75)' \
		-s 'recall_at_precision(min_precision=0.995)' \
		-s 'recall_at_precision(min_precision=0.99)' \
		-s 'recall_at_precision(min_precision=0.98)' \
		-s 'recall_at_precision(min_precision=0.90)' \
		-s 'recall_at_precision(min_precision=0.75)' \
		-s 'recall_at_precision(min_precision=0.60)' \
		-s 'recall_at_precision(min_precision=0.45)' \
		-s 'recall_at_precision(min_precision=0.15)'

major_minor = 0.3
reverted_major_minor = $(major_minor)
damaging_major_minor = $(major_minor)
goodfaith_major_minor = $(major_minor)


{% for wiki in wikis %}
############################# {{ wiki.label }} ################################

{% if "samples" in wiki %}
{% for sample_name, sample in wiki.samples.items() %}
datasets/{{wiki.name}}.sampled_revisions.{{sample_name}}.json:
	wget -qO- {{sample.url}} > $@
{% endfor %}
{% endif %}

{% endfor %}
