name: arwiki
label: Arabic Wikipedia
samples:
    20k_2016:
        quarry_url: "http://quarry.wmflabs.org/run/65713/output/0/json-lines?download=true"

balanced_5k_set_for_review: true

default_sample: 20k_2016

models:
    reverted:
        tuning_params:
            max_depth: 5

host: ar.wikipedia.org
trusted_groups:
    - sysop
    - oversight
    - editor
    - bot
    - rollbacker
    - checkuser
    - abusefilter
    - bureaucrat
