name: arwiki
label: Arabic Wikipedia
host: ar.wikipedia.org

samples:
    20k_2016:
        quarry_url: "http://quarry.wmflabs.org/run/65713/output/0/json-lines?download=true"

balanced_5k_set_for_review: true

default_sample: 20k_2016

models:
    reverted:
        tuning_params:
            max_depth: 5
        pop_rate_true: 0.035186595582635184
        build_number: 1
