name: azwiki
label: Azeri Wikipedia
host: az.wikipedia.org

samples:
    20k_2016:
        quarry_url: "https://quarry.wmflabs.org/run/99533/output/0/json-lines?download=true"

review_samples:
    5k_2016:
        bigger_sample: 20k_2016

trusted_groups:
    - sysop
    - oversight
    - bot
    - rollbacker
    - checkuser
    - abusefilter
    - bureaucrat

default_sample: 20k_2016
