name: bnwikisource
label: Bengali Wikisource
host: bn.wikisource.org

samples:
    200k_2018:
        quarry_url: "https://quarry.wmflabs.org/run/236208/output/0/json-lines?download=true"
        quarry_page: "https://quarry.wmflabs.org/query/24776"

review_samples:
    5k_2018:
        unbalanced: true
        bigger_sample: 200k_2018

default_sample: 200k_2018

models: {}

trusted_groups:
    - bot
    - sysop
