name: cawiki
label: Catalan Wikipedia
host: ca.wikipedia.org

samples:
    100k_2017:
        quarry_url: "https://quarry.wmflabs.org/run/228948/output/0/json-lines?download=true"
        quarry_page: "https://quarry.wmflabs.org/query/24081"

unbalanced_5k_set_for_review: true

default_sample: 100k_2017
review_sample: 5k_2017

models:
    reverted:
        tuning_params:
            n_estimators: 500
        pop_rate_true: 0.01919

trusted_groups:
    - autopatrolled
    - bot
    - bureaucrat
    - checkuser
    - reviewer
    - rollbacker
    - sysop
