name: cswiki
label: Czech Wikipedia
host: cs.wikipedia.org

samples:
    5k_2016:
        labeling_campaign: "https://labels.wmflabs.org/campaigns/cswiki/44/"
    20k_2016:
        quarry_url: "https://quarry.wmflabs.org/run/97125/output/0/json-lines?download=true"

balanced_5k_set_for_review: true

default_sample: 20k_2016
review_sample: 5k_2016

merged_samples:
    20k_2016:
        autolabeled_revisions: "20k_2016"
        human_labeled_revisions: "5k_2016"

models:
    damaging:
        tuning_params:
            n_estimators: 500
        pop_rate_true: 0.0445968266680014
    goodfaith:
        tuning_params:
            max_depth: 5
            n_estimators: 500
        pop_rate_true: 0.977526402722859
