name: eswikiquote
label: Spanish Wikiquote
host: es.wikiquote.org

samples:
    5k_2017:
        labeling_campaign: "https://labels.wmflabs.org/campaigns/eswikiquote/64/"
    12k_2017:
        quarry_url: "https://quarry.wmflabs.org/run/219894/output/0/json-lines?download=true"
        quarry_page: "https://quarry.wmflabs.org/query/23421"

unbalanced_5k_set_for_review: true

default_sample: 12k_2017
review_sample: 5k_2017

merged_samples:
    12k_2017:
        autolabeled_revisions: "12k_2017"
        human_labeled_revisions: "5k_2017"

models:
    damaging:
        tuning_params:
            n_estimators: 700
            max_depth: 7
            learning_rate: 0.01
        pop_rate_true: 0.08707101597009854
    goodfaith:
        tuning_params:
            learning_rate: 1
        pop_rate_true: 0.9356099218484539

trusted_groups:
    - sysop
    - oversight
    - bot
    - rollbacker
    - checkuser
    - abusefilter
    - bureaucrat
    - autopatrolled
