name: eswikibooks
label: Spanish Wikibooks
host: es.wikibooks.org

samples:
    5k_2015:
        labeling_campaign: "https://labels.wmflabs.org/campaigns/eswikibooks/42/"
    20k_2015:
        quarry_url: "https://quarry.wmflabs.org/run/113419/output/0/json-lines?download=true"

default_sample: 20k_2015
review_sample: 5k_2015

merged_samples:
    20k_2015:
        autolabeled_revisions: "20k_2015"
        human_labeled_revisions: "5k_2015"

models:
    damaging:
        tuning_params:
            n_estimators: 500
            max_depth: 3
            learning_rate: 0.1
        pop_rate_true: 0.1126671580499105
    goodfaith:
        tuning_params:
            learning_rate: 0.5
        pop_rate_true: 0.9139393939393939

trusted_groups:
    - sysop
    - oversight
    - bot
    - rollbacker
    - checkuser
    - abusefilter
    - bureaucrat
    - autopatrolled
