name: hewiki
label: Hebrew Wikipedia
host: he.wikipedia.org

external_samples:
  sampled_revisions.20k_2015:
    quarry_url: http://quarry.wmflabs.org/run/42222/output/0/json-lines?download=true
  human_labeled_revisions.5k_2015:
    labeling_campaign: https://labels.wmflabs.org/campaigns/hewiki/25/
  sampled_revisions.20k_2019:
    quarry_page: https://quarry.wmflabs.org/query/33235
    quarry_url: https://quarry.wmflabs.org/run/332742/output/0/json-lines

autolabeled_samples:
  trusted_edits: 1000
  trusted_groups:
   - sysop
   - oversight
   - bot
   - rollbacker
   - checkuser
   - abusefilter
   - bureaucrat
  labeled_samples:
    autolabeled_revisions.20k_2015: sampled_revisions.20k_2015
    autolabeled_revisions.20k_2019: sampled_revisions.20k_2019

balanced_5k_samples:
  revisions_for_review.5k_2015: autolabeled_revisions.20k_2015

merged_samples:
  labeled_revisions.20k_2015:
    - human_labeled_revisions.5k_2015
    - autolabeled_revisions.20k_2015

extracted_samples:
  labeled_revisions.w_cache.20k_2015:
    sample: labeled_revisions.20k_2015
    features_for:
      - damaging
      - goodfaith

models:
  damaging:
    observations: labeled_revisions.w_cache.20k_2015
    label: damaging
    pop_rate_true: 0.046281731975314835
    tune: true
    cv_train:
      algorithm: RandomForest
      parameters:
        criterion: entropy
        max_features: log2
        min_samples_leaf: 1
        n_estimators: 320
  goodfaith:
    observations: labeled_revisions.w_cache.20k_2015
    label: goodfaith
    pop_rate_true: 0.9718244945060459
    tune: true
    cv_train:
      algorithm: GradientBoosting
      parameters:
        learning_rate: 0.1
        max_depth: 7
        max_features: log2
        n_estimators: 300
