name: iswiki
label: Icelandic Wikipedia
host: is.wikipedia.org

samples:
    20k_2017:
        quarry_url: "https://quarry.wmflabs.org/run/218976/output/0/json-lines?download=true"
        quarry_page: "https://quarry.wmflabs.org/query/23305"

trusted_groups:
    - autopatrolled
    - bot
    - bureaucrat
    - checkuser
    - reviewer
    - rollbacker
    - sysop

unbalanced_5k_set_for_review: true

default_sample: 20k_2017
review_sample: 5k_2017

models:
    reverted:
        tuning_params:
            n_estimators: 300
            learning_rate: 0.1
        pop_rate_true: 0.08115405770288514
