name: rowiki
label: Romanian Wikipedia
host: ro.wikipedia.org

samples:
    5k_2016:
        labeling_campaign: "https://labels.wmflabs.org/campaigns/rowiki/48/"
    20k_2016:
        quarry_url: "https://quarry.wmflabs.org/run/146926/output/0/json-lines?download=true"

default_sample: 20k_2016
review_sample: 20k_2016

merged_samples:
    20k_2016:
        autolabeled_revisions: "20k_2016"
        human_labeled_revisions: "5k_2016"

models:
    damaging:
        tuning_params:
            max_depth: 5
        pop_rate_true: 0.04956982793117247
        build_number: 1
    goodfaith:
        tuning_params:
            n_estimators: 300
            max_depth: 3
            learning_rate: 0.1
        pop_rate_true: 0.9699379751900761
        build_number: 1

trusted_groups:
    - abusefilter
    - arbcom
    - bureaucrat
    - checkuser
    - rollbacker
    - sysop
    - bot
    - templateeditor
    - patroller
    - autopatrolled
