name: ruwiki
label: Russian Wikipedia
host: ru.wikipedia.org

samples:
    5k_2015:
        labeling_campaign: "https://labels.wmflabs.org/campaigns/ruwiki/10/"
    20k_2015:
        quarry_url: "https://quarry.wmflabs.org/run/48649/output/0/json-lines?download=true"

default_sample: 20k_2015
review_sample: 20k_2015

merged_samples:
    20k_2015:
        autolabeled_revisions: "20k_2015"
        human_labeled_revisions: "5k_2015"

models:
    damaging:
        tuning_params:
            max_depth: 5
        pop_rate_true: 0.053479185657854755
    goodfaith:
        tuning_params:
            n_estimators: 300
            max_depth: 3
            learning_rate: 0.1
        pop_rate_true: 0.9713866099463182

trusted_groups:
    - abusefilter
    - arbcom
    - bureaucrat
    - checkuser
    - rollbacker
    - sysop
    - bot
