name: zhwiki
label: Chinese Wikipedia
host: zh.wikipedia.org

samples:
    100k_2016:
        quarry_url: "https://quarry.wmflabs.org/run/131979/output/0/json-lines?download=true"

trusted_groups:
    - checkuser
    - bureaucrat
    - sysop
    - eliminator
    - bot

default_sample: 100k_2016

review_samples:
    5k_2016:
        balanced: true
        bigger_sample: 100k_2016
